// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Item in *Achievement → AchievementImage *
 */
export interface AchievementDocumentDataAchievementimageItem {
  /**
   * image field in *Achievement → AchievementImage *
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: achievement.achievementimage[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Achievement documents
 */
interface AchievementDocumentData {
  /**
   * AchievementImage  field in *Achievement*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: achievement.achievementimage[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  achievementimage: prismic.GroupField<
    Simplify<AchievementDocumentDataAchievementimageItem>
  >;
}

/**
 * Achievement document from Prismic
 *
 * - **API ID**: `achievement`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AchievementDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<AchievementDocumentData>,
    "achievement",
    Lang
  >;

/**
 * Content for community documents
 */
interface CommunityDocumentData {
  /**
   * image field in *community*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: community.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *community*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: community.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *community*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: community.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * name field in *community*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: community.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * poc field in *community*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: community.poc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  poc: prismic.NumberField;

  /**
   * link field in *community*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: community.link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * community document from Prismic
 *
 * - **API ID**: `community`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CommunityDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CommunityDocumentData>,
    "community",
    Lang
  >;

/**
 * Item in *Event → images*
 */
export interface EventDocumentDataImagesItem {
  /**
   * image field in *Event → images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Event documents
 */
interface EventDocumentData {
  /**
   * Cover Image field in *Event*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: event.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Event Number field in *Event*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: event.event_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  event_number: prismic.NumberField;

  /**
   * Name field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * Date field in *Event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * end date field in *Event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event.end_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  end_date: prismic.DateField;

  /**
   * Description field in *Event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * images field in *Event*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: event.images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<Simplify<EventDocumentDataImagesItem>>;
}

/**
 * Event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventDocumentData>, "event", Lang>;

/**
 * Content for Members documents
 */
interface MembersDocumentData {
  /**
   * name field in *Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: members.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * image field in *Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: members.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * position field in *Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: members.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  position: prismic.RichTextField;

  /**
   * position_number field in *Members*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: members.position_number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  position_number: prismic.NumberField;

  /**
   * contact details field in *Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: members.contact_details
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  contact_details: prismic.RichTextField;
}

/**
 * Members document from Prismic
 *
 * - **API ID**: `members`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MembersDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<MembersDocumentData>,
    "members",
    Lang
  >;

/**
 * Content for petition documents
 */
interface PetitionDocumentData {
  /**
   * image field in *petition*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: petition.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * number field in *petition*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: petition.number
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  number: prismic.NumberField;

  /**
   * issue name field in *petition*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: petition.issue_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  issue_name: prismic.RichTextField;

  /**
   * Petition Issue Details field in *petition*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: petition.petition_issue_details
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  petition_issue_details: prismic.RichTextField;
}

/**
 * petition document from Prismic
 *
 * - **API ID**: `petition`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PetitionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PetitionDocumentData>,
    "petition",
    Lang
  >;

/**
 * Item in *Upcoming Event → UpcomingImage*
 */
export interface UpcomingEventDocumentDataUpcomingeventimageItem {
  /**
   * image field in *Upcoming Event → UpcomingImage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: upcoming_event.upcomingeventimage[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Content for Upcoming Event documents
 */
interface UpcomingEventDocumentData {
  /**
   * UpcomingImage field in *Upcoming Event*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: upcoming_event.upcomingeventimage[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  upcomingeventimage: prismic.GroupField<
    Simplify<UpcomingEventDocumentDataUpcomingeventimageItem>
  >;
}

/**
 * Upcoming Event document from Prismic
 *
 * - **API ID**: `upcoming_event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type UpcomingEventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<UpcomingEventDocumentData>,
    "upcoming_event",
    Lang
  >;

export type AllDocumentTypes =
  | AchievementDocument
  | CommunityDocument
  | EventDocument
  | MembersDocument
  | PetitionDocument
  | UpcomingEventDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AchievementDocument,
      AchievementDocumentData,
      AchievementDocumentDataAchievementimageItem,
      CommunityDocument,
      CommunityDocumentData,
      EventDocument,
      EventDocumentData,
      EventDocumentDataImagesItem,
      MembersDocument,
      MembersDocumentData,
      PetitionDocument,
      PetitionDocumentData,
      UpcomingEventDocument,
      UpcomingEventDocumentData,
      UpcomingEventDocumentDataUpcomingeventimageItem,
      AllDocumentTypes,
    };
  }
}
